language: cpp
cache: ccache
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: trusty
      services: docker
      git:
       clone: true
       submodules: false
      addons:
        apt:
          packages:
            - p7zip-full
      install: 
       - docker pull quriouspixel/yuzu:latest
      script: 
       - mkdir -p "$HOME/.ccache"
       - docker run -u root -e ENABLE_COMPATIBILITY_REPORTING --env-file .travis/travis-ci.env -v $(pwd):/yuzu -v "$HOME/.ccache":/root/.ccache --name yuzu_appimage quriouspixel/yuzu:latest /bin/bash /yuzu/.travis/docker.sh
      after_success:
      - ls -al artifacts/
      - wget -c https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
      - tar xfv ghr_v0.13.0_linux_amd64.tar.gz      
      - version=$(ls artifacts/version |grep Yuzu-EA | cut -d "-" -f 3 | cut -d "." -f 1) 
      - ghr_v0.13.0_linux_amd64/ghr -recreate -n 'Continous build' -b "Travis CI build log ${TRAVIS_BUILD_WEB_URL}" continuous artifacts/
      - ghr_v0.13.0_linux_amd64/ghr -recreate -n 'EA-$version' -b "Travis CI build log ${TRAVIS_BUILD_WEB_URL}" continuous artifacts/version/
      branches:
  except:
    - /^(?i:continuous.*)$/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
#  secure: 
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
#  on:
#    tags: true
